# Generated by Django 3.1.4 on 2020-12-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageleader',
            name='party',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
