# Generated by Django 3.1.4 on 2020-12-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_imageleader_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageleader',
            name='fulldescripton',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='imageleader',
            name='manifesto',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='imageleader',
            name='party',
            field=models.CharField(default='', max_length=200),
        ),
    ]
