# Generated by Django 3.1.4 on 2020-12-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201215_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageleader',
            name='manifesto',
        ),
        migrations.AddField(
            model_name='imageleader',
            name='manifesto1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='imageleader',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
