# Generated by Django 3.1.4 on 2020-12-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201215_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageleader',
            name='manifesto2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='imageleader',
            name='manifesto3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
