# Generated by Django 3.1.4 on 2020-12-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201215_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageleader',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imageleader',
            name='fulldescripton',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
