# Generated by Django 3.1.4 on 2020-12-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_yo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RenameField(
            model_name='imageleader',
            old_name='fulldescripton',
            new_name='fulldescription',
        ),
    ]
