# Generated by Django 3.1.4 on 2020-12-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201227_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageleader',
            name='fulldescription',
        ),
        migrations.AddField(
            model_name='imageleader',
            name='description1',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
